//------------------------------------------------------------------------------
// <auto-generated>
// Suppress stylecop rules to avoid fixing all these warnings right now.
// </auto-generated>
//------------------------------------------------------------------------------

using Dalamud.Game.Text;
using Dalamud.Game.Text.SeStringHandling.Payloads;

namespace Dalamud.ContextMenu;

using System;
using Dalamud.Game.Text.SeStringHandling;

/// <summary>
/// A custom context menu item
/// </summary>
public abstract class CustomContextMenuItem<T> : BaseContextMenuItem
    where T : Delegate {
    internal IntPtr Agent { get; set; }

    /// <summary>
    /// The name of the context item to be shown for English clients.
    /// </summary>
    public SeString NameEnglish { get; set; }

    /// <summary>
    /// The name of the context item to be shown for Japanese clients.
    /// </summary>
    public SeString NameJapanese { get; set; }

    /// <summary>
    /// The name of the context item to be shown for French clients.
    /// </summary>
    public SeString NameFrench { get; set; }

    /// <summary>
    /// The name of the context item to be shown for German clients.
    /// </summary>
    public SeString NameGerman { get; set; }

    /// <summary>
    /// The action to perform when this item is clicked.
    /// </summary>
    public T Action { get; set; }

    /// <summary>
    /// Create a new context menu item.
    /// </summary>
    /// <param name="name">the English name of the item, copied to other languages</param>
    /// <param name="action">the action to perform on click</param>
    /// <param name="useDalamudIndicator">append the dalamud indicator (red D) to the name.</param>
    internal CustomContextMenuItem(SeString name, T action, bool useDalamudIndicator)
    {
        if (useDalamudIndicator) name = AddDalamudIndicator(name);
        this.NameEnglish = name;
        this.NameJapanese = name;
        this.NameFrench = name;
        this.NameGerman = name;
        this.Action = action;
    }

    private SeString AddDalamudIndicator(SeString name)
    {
        return new SeString().Append(new UIForegroundPayload(539)).Append($"{SeIconChar.BoxedLetterD.ToIconString()} ")
            .Append(new UIForegroundPayload(0)).Append(name);
    }
}