//------------------------------------------------------------------------------
// <auto-generated>
// Suppress stylecop rules to avoid fixing all these warnings right now.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Dalamud.ContextMenu;

using System;
using Dalamud.Game.Text.SeStringHandling;

/// <summary>
/// Arguments for the context menu item selected delegate.
/// </summary>
public class GameObjectContextMenuItemSelectedArgs : BaseContextMenuArgs {
    internal GameObjectContextMenuItemSelectedArgs(IntPtr addon, IntPtr agent, string? parentAddonName, uint objectId, uint contentIdLower, SeString? text, ushort objectWorld) : base(addon, agent, parentAddonName, objectId, contentIdLower, text, objectWorld) {
    }
}