//------------------------------------------------------------------------------
// <auto-generated>
// Suppress stylecop rules to avoid fixing all these warnings right now.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Dalamud.ContextMenu;

using System;
using System.Collections.Generic;
using Dalamud.Game.Text.SeStringHandling;

/// <summary>
/// Arguments for the context menu event.
/// </summary>
public class GameObjectContextMenuOpenArgs : BaseContextMenuArgs {

    internal GameObjectContextMenuOpenArgs(IntPtr addon, IntPtr agent, string? parentAddonName, uint objectId, uint contentIdLower, SeString? text, ushort objectWorld) : base(addon, agent, parentAddonName, objectId, contentIdLower, text, objectWorld) {
    }
    
    /// <summary>
    /// Gets context menu items in this menu.
    /// </summary>
    internal List<BaseContextMenuItem> Items { get; } = new();
    
    /// <summary>
    /// Add custom item to context menu items.
    /// </summary>
    /// <param name="item">context menu item.</param>
    public void AddCustomItem(GameObjectContextMenuItem item)
    {
        this.Items.Add(item);
    }
}