//------------------------------------------------------------------------------
// <auto-generated>
// Suppress stylecop rules to avoid fixing all these warnings right now.
// </auto-generated>
//------------------------------------------------------------------------------

using Dalamud.Game.Text.SeStringHandling;

namespace Dalamud.ContextMenu;

using System;
using System.Collections.Generic;

/// <summary>
/// The arguments for when an inventory context menu is opened
/// </summary>
public class InventoryContextMenuOpenArgs : BaseInventoryContextMenuArgs {

    internal InventoryContextMenuOpenArgs(IntPtr addon, IntPtr agent, string? parentAddonName, uint itemId, uint itemAmount, bool itemHq) : base(addon, agent, parentAddonName, itemId, itemAmount, itemHq) {
    }
    
    
    /// <summary>
    /// Gets context menu items in this menu.
    /// </summary>
    internal List<BaseContextMenuItem> Items { get; } = new();

    /// <summary>
    /// Add custom item to context menu items.
    /// </summary>
    /// <param name="item">context menu item.</param>
    public void AddCustomItem(InventoryContextMenuItem item)
    {
        this.Items.Add(item);
    }
}