//------------------------------------------------------------------------------
// <auto-generated>
// Suppress stylecop rules to avoid fixing all these warnings right now.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Dalamud.ContextMenu;

using Dalamud.Game.Text.SeStringHandling;

/// <summary>
/// A custom context menu item for inventory items.
/// </summary>
public class InventoryContextMenuItem : CustomContextMenuItem<Dalamud.ContextMenu.ContextMenu.InventoryContextMenuItemSelectedDelegate> {
    /// <summary>
    /// Create a new context menu item for inventory items.
    /// </summary>
    /// <param name="name">the English name of the item, copied to other languages</param>
    /// <param name="action">the action to perform on click</param>
    public InventoryContextMenuItem(SeString name, Dalamud.ContextMenu.ContextMenu.InventoryContextMenuItemSelectedDelegate action) : base(name, action) {
    }
}