using System;

namespace XivCommon.Functions.Tooltips {
    public enum ItemTooltipString {
        Name = 0,
        GlamourName = 1,
        Type = 2,
        Description = 13,
        Quantity = 14,
        Level = 27,
        EffectsLabel = 15,
        Effects = 16,
        VendorSellPrice = 25,
        VendorBuyPrice = 63,
        Crafter = 26,
        Stat1Label = 4,
        Stat1 = 7,
        Stat1Delta = 10,
        Stat2Label = 5,
        Stat2 = 8,
        Stat2Delta = 11,
        Stat3Label = 6,
        Stat3 = 9,
        Stat3Delta = 12,
        EquipJobs = 22,
        EquipLevel = 23,
        Condition = 28,
        SpriritbondLabel = 29,
        Spiritbond = 30,
        RepairLevel = 31,
        Materials = 32,
        QuickRepairs = 33,
        MateriaMelding = 34,
        AbleToDoShit = 35,
        BonusesLabel = 36,
        Bonus1 = 37,
        Bonus2 = 38,
        Bonus3 = 39,
        Bonus4 = 40,
        MateriaLabel = 52,
        Materia1 = 53,
        Materia2 = 54,
        Materia3 = 55,
        Materia4 = 56,
        Materia5 = 57,
        Materia1Effect = 58,
        Materia2Effect = 59,
        Materia3Effect = 60,
        Materia4Effect = 61,
        Materia5Effect = 62,
        ControllerControls = 64,
    }


    [Flags]
    public enum ItemTooltipFields {
        Crafter = 1 << 0,
        Description = 1 << 1,
        VendorSellPrice = 1 << 2,
        // something to do with glamour - controls whether the little + symbol on the item icon appears
        Unknown10 = 1 << 10,
        Stat1 = 1 << 11,
        Stat2 = 1 << 12,
        Stat3 = 1 << 13,
        Unknown19 = 1 << 19,
    }
}
