//------------------------------------------------------------------------------
// <auto-generated>
// Suppress stylecop rules to avoid fixing all these warnings right now.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Dalamud.ContextMenu;

using System;

/// <summary>
/// A base class for accessing DalamudContextMenu functionality.
/// </summary>
public class DalamudContextMenuBase : IDisposable {
    /// <summary>
    /// Game functions and events
    /// </summary>
    public GameFunctions Functions { get; }

    /// <summary>
    /// <para>
    /// Construct a new Dalamud.ContextMenu base.
    /// </para>
    /// <para>
    /// This will automatically enable hooks based on the hooks parameter.
    /// </para>
    /// </summary>
    public DalamudContextMenuBase() {
        this.Functions = new GameFunctions();
    }

    /// <inheritdoc />
    public void Dispose() {
        this.Functions.Dispose();
    }
}