//------------------------------------------------------------------------------
// <auto-generated>
// Suppress stylecop rules to avoid fixing all these warnings right now.
// </auto-generated>
//------------------------------------------------------------------------------

using Dalamud.Game;
using Dalamud.Game.ClientState;
using Dalamud.Game.Gui;
namespace Dalamud.ContextMenu;

using System;

/// <summary>
/// A base class for accessing DalamudContextMenu functionality.
/// </summary>
public class DalamudContextMenu : IDisposable {
    private GameGui GameGui { get; }

    private Dalamud.Game.Framework Framework { get; }

    internal UiAlloc UiAlloc { get; }

    /// <summary>
    /// Context menu functions
    /// </summary>
    public ContextMenu ContextMenu { get; }

    /// <summary>
    /// <para>
    /// Construct a new Dalamud.ContextMenu base.
    /// </para>
    /// <para>
    /// This will automatically enable hooks based on the hooks parameter.
    /// </para>
    /// </summary>
    public DalamudContextMenu() {
        this.Framework = Util.GetService<Dalamud.Game.Framework>();
        this.GameGui = Util.GetService<GameGui>();

        var clientState = Util.GetService<ClientState>();
        var scanner = Util.GetService<SigScanner>();

        this.UiAlloc = new UiAlloc(scanner);
        this.ContextMenu = new ContextMenu(this, scanner, clientState.ClientLanguage);
    }

    /// <inheritdoc />
    public void Dispose() {
        this.ContextMenu.Dispose();
    }
}