//------------------------------------------------------------------------------
// <auto-generated>
// Suppress stylecop rules to avoid fixing all these warnings right now.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Dalamud.ContextMenu;

using System;
using Dalamud.Game;
using Dalamud.Game.ClientState;
using Dalamud.Game.Gui;

/// <summary>
/// A class containing game functions
/// </summary>
public class GameFunctions : IDisposable {
    private GameGui GameGui { get; }

    private Dalamud.Game.Framework Framework { get; }

    internal UiAlloc UiAlloc { get; }

    /// <summary>
    /// Context menu functions
    /// </summary>
    public ContextMenu ContextMenu { get; }

    internal GameFunctions() {
        this.Framework = Util.GetService<Dalamud.Game.Framework>();
        this.GameGui = Util.GetService<GameGui>();

        var clientState = Util.GetService<ClientState>();
        var scanner = Util.GetService<SigScanner>();

        this.UiAlloc = new UiAlloc(scanner);
        this.ContextMenu = new ContextMenu(this, scanner, clientState.ClientLanguage);
    }

    /// <inheritdoc />
    public void Dispose() {
        this.ContextMenu.Dispose();
    }
}